export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_WEATHER_DATA = 'SET_WEATHER_DATA';
export const SET_LOCATION_BY_CITY = 'SET_LOCATION_BY_CITY';
export const SET_LOCATION_BY_COORDINATES = 'SET_LOCATION_BY_COORDINATES';
export const SET_FORECAST_DATA = 'SET_FORECAST_DATA';
