export const SET_LOCATION = 'SET_LOCATION';
export const SET_TEMPERATURE = 'SET_TEMPERATURE';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_WEATHER_DATA = 'SET_WEATHER_DATA';
