import type {Metadata} from 'next';
import {Box} from '@mui/material';

import AppProvider from '@/providers/AppProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Box component='body' cz-shortcut-listen='true'>
        <AppProvider>{children}</AppProvider>
      </Box>
    </html>
  );
}
